// Copyright © Timothy van der Ham (@Tim81)
// SPDX-License-Identifier: Apache-2.0

namespace VellumPdf.Barcodes.Aztec;

// Placement is authored from ISO/IEC 24778 clause 7.1 (fixed patterns: finder, orientation,
// reference grid — each given as a closed-form formula over Cartesian coordinates centred on the
// symbol, x right, y up), clause 7.2 (the mode message) and clause 7.3 (the data-layer spiral of
// 2-module "domino" pairs). zint and zxing-cpp are used only as decode/cross-check oracles in this
// package's tests, never as source.

/// <summary>
/// Builds the full Aztec Code module grid: the central bullseye finder pattern, four orientation
/// chevrons, the reference grid (full-range only), the mode message ring immediately surrounding
/// the finder, and the data field's spiral of 2-module "domino" pairs.
///
/// <para>
/// <b>Data-layer placement provenance.</b> ISO/IEC 24778's own data-placement figures (Figures 4
/// and 5) are raster diagrams absent from the freely available preview pages, so the spiral geometry
/// here was derived from, and verified bit-for-bit against, module matrices generated by zxing-cpp
/// (used purely as an oracle — its source is never read or copied). The rule was solved by aligning
/// this package's own codeword bit stream to zxing-cpp reference symbols across many sizes and
/// contents simultaneously (a single symbol is ambiguous; the cross-symbol solve is not), then
/// distilled into the parametric algorithm below and confirmed to reproduce every generated
/// reference exactly: compact 1-4 layers and full-range 4-32 layers (including the reference-grid
/// displacement, the codeword-count/word-width transitions, and the sizes that carry a few spare
/// spiral cells). The complementary decode round-trip — render, rasterize, decode with zxing-cpp —
/// is exercised over the whole size range by <c>ZxingDecodeOracleTests</c>.
/// </para>
///
/// <para>
/// <b>The spiral (ISO/IEC 24778 clause 7.3).</b> The data field is a clockwise spiral of concentric
/// 2-module-thick square layers, filled outermost layer inward. Each layer is walked as four edges —
/// left (top to bottom), bottom (left to right), right (bottom to top), top (right to left) — every
/// edge laying down 2-module dominoes that pair the layer's outer-radius cell with its inner-radius
/// cell. The codeword stream (data codewords then error-correction codewords, each most-significant
/// bit first) is placed in that order; when a size's spiral holds a handful more cells than the
/// codewords need, those spare cells fall at the spiral's head (nearest the outer edge) and are left
/// blank. Full-range symbols carry the reference grid at every module whose centred x or y is a
/// multiple of 16: the spiral is laid out on a virtual grid without those lines and mapped outward
/// through them, and the two dominoes per layer that would land on the central reference cross are
/// dropped.
/// </para>
/// </summary>
internal static class AztecPlacement
{
    internal static BarcodeMatrix Build(AztecSymbolSize size, IReadOnlyList<bool> modeMessageBits, IReadOnlyList<int> codewords)
    {
        var half = size.OuterRadius;
        var matrix = new BarcodeMatrix(size.Size, size.Size);
        var f = size.CoreOuterRadius - 1; // the finder-pattern half-width (4 compact, 6 full-range)

        void SetXy(int x, int y, bool dark) => matrix.SetDark(x + half, half - y, dark);

        DrawFinder(SetXy, f);
        DrawOrientation(SetXy, f);
        if (!size.IsCompact) DrawReferenceGrid(SetXy, half);
        DrawModeMessage(SetXy, f, modeMessageBits, isCompact: size.IsCompact);
        DrawDataField(SetXy, size, codewords);

        return matrix;
    }

    /// <summary>ISO/IEC 24778 clause 7.1.2: modules within <c>max(|x|,|y|) &lt;= f</c> encode <c>(max(|x|,|y|) + 1) mod 2</c> (1 = dark).</summary>
    private static void DrawFinder(Action<int, int, bool> setXy, int f)
    {
        for (var y = -f; y <= f; y++)
            for (var x = -f; x <= f; x++)
            {
                var radius = Math.Max(Math.Abs(x), Math.Abs(y));
                setXy(x, y, ((radius + 1) % 2) == 1);
            }
    }

    /// <summary>ISO/IEC 24778 clause 7.1.3: four 3-module chevrons at the finder's corners, given as explicit dark/light coordinates.</summary>
    private static void DrawOrientation(Action<int, int, bool> setXy, int f)
    {
        (int X, int Y)[] dark =
        [
            (-f - 1, f), (-f - 1, f + 1), (-f, f + 1),
            (f + 1, f + 1), (f + 1, f), (f + 1, -f),
        ];
        (int X, int Y)[] light =
        [
            (f, f + 1), (f + 1, -f - 1), (f, -f - 1),
            (-f, -f - 1), (-f - 1, -f - 1), (-f - 1, -f),
        ];

        foreach (var (x, y) in dark) setXy(x, y, true);
        foreach (var (x, y) in light) setXy(x, y, false);
    }

    /// <summary>ISO/IEC 24778 clause 7.1.4 (full-range only): every cell with <c>x</c> or <c>y</c> a multiple of 16 encodes <c>(x + y + 1) mod 2</c>.</summary>
    private static void DrawReferenceGrid(Action<int, int, bool> setXy, int half)
    {
        for (var y = -half; y <= half; y++)
        {
            for (var x = -half; x <= half; x++)
            {
                if (x % 16 != 0 && y % 16 != 0) continue;
                var value = ((x + y + 1) % 2 + 2) % 2;
                setXy(x, y, value == 1);
            }
        }
    }

    /// <summary>
    /// ISO/IEC 24778 clause 7.2.5: the mode message wraps clockwise around the finder starting at
    /// the top-left corner, one bit per cell, most significant bit first, skipping the four
    /// orientation chevrons and — for full-range symbols — the single reference-grid cell at the
    /// centre of each side.
    /// </summary>
    private static void DrawModeMessage(Action<int, int, bool> setXy, int f, IReadOnlyList<bool> bits, bool isCompact)
    {
        var i = 0;
        foreach (var (x, y) in WalkModeMessageRing(f, skipCenter: !isCompact))
            setXy(x, y, bits[i++]);
    }

    private static IEnumerable<(int X, int Y)> WalkModeMessageRing(int f, bool skipCenter)
    {
        for (var x = -(f - 1); x <= f - 1; x++)
            if (!skipCenter || x != 0) yield return (x, f + 1);
        for (var y = f - 1; y >= -(f - 1); y--)
            if (!skipCenter || y != 0) yield return (f + 1, y);
        for (var x = f - 1; x >= -(f - 1); x--)
            if (!skipCenter || x != 0) yield return (x, -(f + 1));
        for (var y = -(f - 1); y <= f - 1; y++)
            if (!skipCenter || y != 0) yield return (-(f + 1), y);
    }

    /// <summary>
    /// Places the data + error-correction codeword bit stream along the data-field spiral (see this
    /// type's remarks): codewords in order, each most-significant bit first, into the spiral's cells
    /// from the outer end inward. Any spare cells at the spiral's head are left blank.
    /// </summary>
    private static void DrawDataField(Action<int, int, bool> setXy, AztecSymbolSize size, IReadOnlyList<int> codewords)
    {
        var spiral = BuildDataSpiral(size);

        var totalBits = codewords.Count * size.WordBits;
        var offset = spiral.Count - totalBits;
        if (offset < 0)
        {
            throw new InvalidOperationException(
                $"Aztec data-field spiral produced only {spiral.Count} cells for a {size.Size}x{size.Size}, " +
                $"{size.Layers}-layer {(size.IsCompact ? "compact" : "full-range")} symbol, but its {codewords.Count} " +
                $"codewords of {size.WordBits} bits need {totalBits} — an internal placement-algorithm defect.");
        }

        // The few sizes whose spiral holds more cells than the codewords fill (e.g. every 1-layer
        // symbol) leave those spare cells, at the spiral's outer head, blank.
        for (var i = 0; i < offset; i++)
            setXy(spiral[i].X, spiral[i].Y, false);

        var bit = 0;
        foreach (var codeword in codewords)
            for (var b = size.WordBits - 1; b >= 0; b--)
            {
                var (x, y) = spiral[offset + bit];
                setXy(x, y, ((codeword >> b) & 1) != 0);
                bit++;
            }
    }

    /// <summary>
    /// The ordered data-field cells, outermost 2-module layer inward, each layer walked as four
    /// domino edges (see this type's remarks). For full-range, cells are laid out on a virtual grid
    /// with no reference lines and then displaced outward through them (<see cref="MapThroughReferenceGrid"/>),
    /// dropping the two dominoes per layer that would fall on the central reference cross.
    /// </summary>
    private static List<(int X, int Y)> BuildDataSpiral(AztecSymbolSize size)
    {
        var coreRadius = size.CoreOuterRadius;
        var spiral = new List<(int X, int Y)>();

        for (var outer = coreRadius + (2 * size.Layers); outer >= coreRadius + 2; outer -= 2)
        {
            foreach (var (x, y) in WalkLayer(outer))
            {
                // A full-range cell on either central axis coincides with the reference grid's
                // central cross, which is fixed structure rather than data.
                if (!size.IsCompact && (x == 0 || y == 0)) continue;

                spiral.Add(size.IsCompact
                    ? (x, y)
                    : (MapThroughReferenceGrid(x), MapThroughReferenceGrid(y)));
            }
        }

        return spiral;
    }

    /// <summary>
    /// One 2-module-thick layer whose outer radius is <paramref name="outer"/> (inner radius one
    /// less), walked clockwise as four edges — left (top to bottom), bottom (left to right), right
    /// (bottom to top), top (right to left) — each domino pairing the outer-radius cell then the
    /// inner-radius cell at that position.
    /// </summary>
    private static IEnumerable<(int X, int Y)> WalkLayer(int outer)
    {
        var inner = outer - 1;

        // Left edge, top to bottom.
        for (var y = outer; y >= -(outer - 2); y--) { yield return (-outer, y); yield return (-inner, y); }
        // Bottom edge, left to right.
        for (var x = -outer; x <= outer - 2; x++) { yield return (x, -outer); yield return (x, -inner); }
        // Right edge, bottom to top.
        for (var y = -outer; y <= outer - 2; y++) { yield return (outer, y); yield return (inner, y); }
        // Top edge, right to left.
        for (var x = outer; x >= -(outer - 2); x--) { yield return (x, outer); yield return (x, inner); }
    }

    /// <summary>
    /// Maps a virtual (reference-line-free) axis coordinate to its physical position, inserting one
    /// reference line every 16 physical modules (ISO/IEC 24778 clause 7.1.4): every run of 15 data
    /// cells is followed by a reference line, so physical positions never land on a multiple of 16.
    /// </summary>
    private static int MapThroughReferenceGrid(int coordinate)
    {
        if (coordinate == 0) return 0;
        var magnitude = Math.Abs(coordinate);
        var physical = magnitude + ((magnitude - 1) / 15);
        return coordinate > 0 ? physical : -physical;
    }
}
