# Copyright © Timothy van der Ham (@Tim81)
# SPDX-License-Identifier: Apache-2.0
#
# One-off generator for src/VellumPdf.Barcodes/Qr/ShiftJisTable.cs. Downloads the Unicode
# Consortium's Shift-JIS-to-Unicode mapping, keeps only the double-byte code points that fall in
# the two Shift-JIS blocks ISO/IEC 18004 §7.4.6 allows in QR Kanji mode (0x8140-0x9FFC and
# 0xE040-0xEBBF), and emits two parallel sorted arrays (Unicode scalar, Shift-JIS code) for a
# binary-search lookup. Re-run this whenever the table needs regenerating; it is not part of the
# build.
#
# Usage: python eng/generate-shiftjis-table.py [path-to-cached-SHIFTJIS.TXT]
# With no argument, fetches the mapping from unicode.org.

import sys
import re
import urllib.request

SOURCE_URL = "https://www.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/JIS/SHIFTJIS.TXT"
OUTPUT_PATH = "src/VellumPdf.Barcodes/Qr/ShiftJisTable.cs"
ENTRY_LINE = re.compile(r"^0x([0-9A-Fa-f]+)\t0x([0-9A-Fa-f]+)")

KANJI_BLOCKS = [(0x8140, 0x9FFC), (0xE040, 0xEBBF)]


def is_kanji_eligible(sjis: int) -> bool:
    return any(low <= sjis <= high for low, high in KANJI_BLOCKS)


def fetch_mapping_text(path: str | None) -> str:
    if path:
        with open(path, encoding="utf-8") as f:
            return f.read()
    with urllib.request.urlopen(SOURCE_URL) as response:
        return response.read().decode("utf-8")


def parse_entries(text: str) -> list[tuple[int, int]]:
    entries = []
    for line in text.splitlines():
        match = ENTRY_LINE.match(line)
        if not match:
            continue
        sjis = int(match.group(1), 16)
        unicode_scalar = int(match.group(2), 16)
        if is_kanji_eligible(sjis):
            entries.append((unicode_scalar, sjis))
    return entries


def format_array(values: list[int], per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        lines.append(", ".join(f"0x{v:04X}" for v in chunk))
    return ",\n        ".join(lines)


def generate_source(entries: list[tuple[int, int]]) -> str:
    entries = sorted(set(entries))
    unicode_scalars = [u for u, _ in entries]
    if len(unicode_scalars) != len(set(unicode_scalars)):
        raise ValueError("duplicate Unicode scalar in the eligible Kanji-block entries")

    shift_jis_codes = [s for _, s in entries]

    return f"""// Copyright © Timothy van der Ham (@Tim81)
// SPDX-License-Identifier: Apache-2.0

namespace VellumPdf.Barcodes.Qr;

/// <summary>
/// Unicode-scalar to Shift-JIS-X-0208 lookup for QR Kanji mode (ISO/IEC 18004 §7.4.6), restricted
/// to the two Shift-JIS blocks the mode allows: 0x8140-0x9FFC and 0xE040-0xEBBF. Generated by
/// <c>eng/generate-shiftjis-table.py</c> from the Unicode Consortium's SHIFTJIS.TXT
/// ({SOURCE_URL}); do not hand-edit.
/// </summary>
internal static class ShiftJisTable
{{
    // Parallel arrays sorted ascending by Unicode scalar, {len(entries)} entries.
    private static readonly int[] UnicodeScalars =
    [
        {format_array(unicode_scalars)},
    ];

    private static readonly int[] ShiftJisCodes =
    [
        {format_array(shift_jis_codes)},
    ];

    /// <summary>
    /// Looks up the Shift-JIS-X-0208 code for <paramref name="unicodeScalar"/>, restricted to the
    /// two blocks QR Kanji mode allows. Returns <see langword="false"/> for any character outside
    /// those blocks, including code points Shift-JIS maps elsewhere (single-byte, half-width
    /// kana, or the user-defined/extension ranges above 0xEBBF).
    /// </summary>
    internal static bool TryGetShiftJis(int unicodeScalar, out int shiftJis)
    {{
        var index = Array.BinarySearch(UnicodeScalars, unicodeScalar);
        if (index < 0)
        {{
            shiftJis = 0;
            return false;
        }}

        shiftJis = ShiftJisCodes[index];
        return true;
    }}
}}
"""


def main() -> int:
    cached_path = sys.argv[1] if len(sys.argv) > 1 else None
    text = fetch_mapping_text(cached_path)
    entries = parse_entries(text)
    if not entries:
        print("no eligible entries parsed from the mapping file", file=sys.stderr)
        return 1

    source = generate_source(entries)
    with open(OUTPUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(source)

    print(f"wrote {len(entries)} entries to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
